version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: carcraze_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
      build: ./backend
      container_name: carcraze_backend
      ports:
        - "5001:5001"
      # --- ADD THESE 3 LINES ---
      dns:
        - 8.8.8.8
        - 1.1.1.1
      # -------------------------
      env_file: 
        - ./backend/.env
      environment:
        - PORT=5001
        - NODE_ENV=development
      depends_on:
        - mongodb # You can safely remove this line and the mongodb service above if you are only using Atlas
        - redis

  frontend:
      build: ./frontend
      container_name: carcraze_frontend
      ports:
        - "5173:5173" # Updated to match Vite
      environment:
        - REACT_APP_API_URL=http://localhost:5001/api
      depends_on:
        - backend
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data: